/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.pkg3;

import javax.swing.JOptionPane;

/**
 *
 * @author TheGunner
 */
public class login_form extends javax.swing.JFrame {

    /**
     * Creates new form login_form
     */
    public login_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seperator = new javax.swing.JPanel();
        Tilesets = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        signup = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        side = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E.M.D's Inventory Syste");
        setBackground(new java.awt.Color(222, 235, 236));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Seperator.setBackground(new java.awt.Color(222, 235, 236));

        javax.swing.GroupLayout SeperatorLayout = new javax.swing.GroupLayout(Seperator);
        Seperator.setLayout(SeperatorLayout);
        SeperatorLayout.setHorizontalGroup(
            SeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SeperatorLayout.setVerticalGroup(
            SeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(Seperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 10, 370));

        Tilesets.setBackground(new java.awt.Color(190, 217, 221));

        title1.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("E.M.D's Login");

        title.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Members:");

        javax.swing.GroupLayout TilesetsLayout = new javax.swing.GroupLayout(Tilesets);
        Tilesets.setLayout(TilesetsLayout);
        TilesetsLayout.setHorizontalGroup(
            TilesetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TilesetsLayout.createSequentialGroup()
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TilesetsLayout.setVerticalGroup(
            TilesetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Tilesets, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        main.setBackground(new java.awt.Color(115, 179, 178));
        main.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        main.add(jLabel2);
        jLabel2.setBounds(6, 65, 69, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        main.add(jLabel3);
        jLabel3.setBounds(6, 105, 65, 20);
        main.add(username);
        username.setBounds(93, 65, 220, 22);
        main.add(password);
        password.setBounds(93, 105, 220, 22);

        signup.setBackground(new java.awt.Color(60, 151, 159));
        signup.setText("SignUp");
        signup.setBorderPainted(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        main.add(signup);
        signup.setBounds(209, 324, 175, 40);

        login.setBackground(new java.awt.Color(60, 151, 159));
        login.setText("Login");
        login.setBorderPainted(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        main.add(login);
        login.setBounds(6, 324, 175, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group/pkg3/139e71e9-5f5c-4895-96e0-c9dc82ab8ef7-removebg-preview.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        main.add(jLabel4);
        jLabel4.setBounds(30, 30, 340, 300);

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 370));

        side.setBackground(new java.awt.Color(174, 207, 208));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html>Emron Gabriel Ducalan <br>\nRhema Monique Bangis <br>\nMark Jerald pine <br>\nGuarino<br>\nAina Lim<br>\nPayos<br>\nSeniedo<br></html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(side, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        InventorySystem base = new InventorySystem();
        String a = username.getText();
        char[] passwordChars = password.getPassword();
        String passwords = new String(passwordChars).trim(); // Convert to String
        String b = passwords;
        if (base.login(a,b)){
            this.setVisible(false);
            MainInterface panel = new MainInterface();
            panel.setBounds(this.getX(), this.getY(), 1360 , 750);
            panel.setVisible(true);
            this.dispose();
        } else {
            alert("Invalid Login");
        }

    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        InventorySystem base = new InventorySystem();
        String a = username.getText();
        char[] passwordChars = password.getPassword();
        String passwords = new String(passwordChars).trim(); // Convert to String
        String b = passwords;
        if (base.registerUser(a,b)){
            alert("Registered");
        } else {
            alert("Invalid Register");
        }
    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_form().setVisible(true);
            }
        });
    }

    public static void alert(String message){
        JOptionPane.showMessageDialog(null, message, "Hey!", JOptionPane.PLAIN_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Seperator;
    private javax.swing.JPanel Tilesets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JPanel main;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel side;
    private javax.swing.JButton signup;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
